all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_become: true
    ansible_ssh_private_key_file: <private_key_file>
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

zookeeper:
  hosts:
    <zookeeper-1>

kafka_broker:
  hosts:
    <kafka-0>
    <kafka-1>
    <kafka-2>

schema_registry:
  hosts:
    <schema_registry_server>